drop table ROOM_MANAGE PURGE;
drop table DORM_STUDENTS_MANAGE PURGE;
drop table CAFETERIA_MANAGE PURGE;
drop table STAYOUT_MANAGE PURGE;

create table ROOM_MANAGE(
    R_RNUM VARCHAR2(6) NOT NULL,
    R_RPERSON NUMBER(2),
    R_STU_A VARCHAR2(15),
    R_STU_B VARCHAR2(15),
    R_ISA CHAR(1) CONSTRAINT BOOLEAN_ISA_CK CHECK(R_ISA IN ('0', '1')),
    R_ISB CHAR(1) CONSTRAINT BOOLEAN_ISB_CK CHECK(R_ISB IN ('0', '1')),
    CONSTRAINT PK_R_RNUM PRIMARY KEY(R_RNUM)
);
    

create table DORM_STUDENTS_MANAGE(
    D_SNAME VARCHAR2(15) NOT NULL,
    D_SNUM NUMBER(8) NOT NULL,
    D_MAJOR VARCHAR2(30),
    D_BADPOINT NUMBER(4),
    D_GOODPOINT NUMBER(4),
    D_RNUM VARCHAR2(6) NOT NULL,
    D_RPOSITION VARCHAR2(2) NOT NULL,
    D_OUTDATE NUMBER(2),
    D_SEX CHAR(4),
    D_PHONENUM CHAR(13),
    CONSTRAINT PK_D_SNUM PRIMARY KEY(D_SNUM),
    CONSTRAINT FK_D_RNUM FOREIGN KEY(D_RNUM) REFERENCES ROOM_MANAGE(R_RNUM) ON DELETE CASCADE
);

create table CAFETERIA_MANAGE(
    C_BREAKFAST VARCHAR2(45),
    C_LUNCH VARCHAR2(45),
    C_DINNER VARCHAR2(45),
    C_DATE DATE NOT NULL,
    C_PRICE NUMBER(8),
    CONSTRAINT PK_C_DATE PRIMARY KEY(C_DATE) 
);

create table STAYOUT_MANAGE(
    S_SNAME VARCHAR2(15) NOT NULL,
    S_SNUM NUMBER(8) NOT NULL,
    S_RNUM VARCHAR2(6) NOT NULL,
    S_APPLY CHAR(1) CONSTRAINT BOOLEAN_APPLY_CK CHECK(S_APPLY IN ('0', '1')),
    S_DATE DATE NOT NULL,
    CONSTRAINT PK_S_SNUM PRIMARY KEY(S_SNUM),
    CONSTRAINT FK_S_SNUM FOREIGN KEY(S_SNUM) REFERENCES DORM_STUDENTS_MANAGE(D_SNUM) ON DELETE CASCADE,
    CONSTRAINT FK_S_RNUM FOREIGN KEY(S_RNUM) REFERENCES ROOM_MANAGE(R_RNUM) ON DELETE CASCADE
);
